### ISSUE TITLE
TODO Items

### ISSUE THREAD

**Issue by cazier** [cazier/troupy#1]
Eventually I'd like to add support for some or all of the following:

- [ ] Automatically sync files from the server to the local filesystem (using [tvenamr](https://github.com/ghickman/tvrenamr))
- [ ] Create a more installable executable (for things like pip)
- [ ] Better notification system (Something that let's me use Gmail/any other email provider, push, texts (?), etc.)
- [ ] Better documentation
- [ ] Thorough logging
- [ ] Actual readme...
