### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by cazier** [cazier/troupy#2]
- [ ] Add support to synchronize the files from the freeze plug to the local filesystem
- [ ] Renaming files with the use of [tvr] (https://github.com/ghickman/tvrenamr)
- [ ] Better notifications (maybe using [click](http://click.pocoo.org/5/))
- [ ] Add support for multifile/.rar files
